apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: inventory-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: dipeshtal/k8-ws-java-inventory-service
        ports:
        - containerPort: 8082